### PR TITLE
TODO list update

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This pull request will set the singularity_build.sh and test it with docker-compose.yml across CentOS-Fedora-Ubuntu.

Travis will test the latest stable release.

Fixes

 - Fix the use of the "Update" Command

Changes:

 - Change .travis.yml language form ruby to cpp
 - Change the README.md

Creates files
 - docker-compose.yml
 - dockerfile for :
    - fedora
    - ubuntu
    - centos

Creates folders for dockerfiles:
 - fedora
 - ubuntu
 - centos

Ready for review!

### CODE REVIEW

**Comment by vsoch** [comment]
docker-compose is traditionally used in a context where you need to orchestrate different containers together. In this case we have isolated tests for different environments, and it gets funky because each line in travis isn't necessarily the same process running. I think it would be best to remove compose and run the docker containers as it, with a clear script to run the install, collect the return value, and return successful test given return value 0.

**Comment by ArangoGutierrez** [comment]
From the TODO list issue #3 
- [x]  get base tests working
- [x]  addition of --prefix specification, and testing
- [ ]  testing of install then selftest
- [ ] testing of development functions
- [x]  addition and testing of a clean function
- [ ]  add cache to testing so we don't need to always rebuild docker images
- [ ]  add remaining OS to tests

Also adds:
 - Clean command to the README.md

Also Fix:
 - check for SINGULARITY_PATH in remove  function
 - Install function breaks if clone function wasn't run before

**Comment by vsoch** [comment]
It's probably a better idea to have these variables set, or not. When you are checking for a particular string you run into issues of needing to check for `True` `TRUE` `T` `1` or whatever variation of True there is.

**Comment by ArangoGutierrez** [comment]
Hi! you mean a rollback on "Enhanced variable delcaration" commit?  Any comments on the other commits?

**Pull request closed without merging**
